### ISSUE TITLE
Invalid 'line': out of range

### ISSUE THREAD

**Issue by jacobrreed** [tomasky/bookmarks.nvim#14]
![image](https://github.com/tomasky/bookmarks.nvim/assets/25580051/834088e5-6a3b-4cfc-9a6e-a5992e137771)

Not sure what's going on, everytime I enter window i'm getting this error. Clearing all bookmarks and adding a new one gets rid of the error.

**Comment by gosticks** [comment]
Had the same issue, for me it was caused by a mark being present outside of the buffer line length. I have posted a PR #18  with a quick fix.

**Comment by jacobrreed** [comment]
@tomasky can you merge this
