### ISSUE TITLE
Bug: signs aren't loaded on startup

### ISSUE THREAD

**Issue by chrisgrieser** [tomasky/bookmarks.nvim#4]
Thanks for this plugin, wouldn't have found it if it wasn't just listed recently (#1).

I noticed that the signs (in the signcolumn) do not appear on initial startup. The bookmarks are there and work for going to the next bookmark, but the signs only appear after you switch to a different buffer and then switch back.

I have tried it without lazyloading, still the same issue. I also tried disabling other plugins that add things to the signcolumn (e.g. gitsigns) in case of conflicts there, but the issue persists even then

**Comment by tomasky** [comment]
i will test it, Please provide your   steps  or some video  to reproduce

**Comment by chrisgrieser** [comment]
yeah sure, here an example video

https://user-images.githubusercontent.com/73286100/233785846-1e3dff22-3440-4602-a4a5-31af34e359ff.mp4

**Comment by tomasky** [comment]
This should be fixed. check it or reopen this

**Comment by chrisgrieser** [comment]
Hmm, now it looks like the signs are completely gone. They do appear when adding a new bookmark, but after restart, they do not re-appear, even after switching buffer

**Comment by tomasky** [comment]
sorry ,I don't understand what you mean, i have test it and it should work. you can provide other video.

**Comment by tomasky** [comment]
you can use command `ml` to check the bookmark list

**Comment by chrisgrieser** [comment]
yes, here see the video. after nvim restart, the signs do not show up. they only appear when switching the app

https://user-images.githubusercontent.com/73286100/233794897-634439bb-c061-4577-9a0b-c12ff15b5f60.mp4

**Comment by chrisgrieser** [comment]
> you can use command ml to check the list of bookmarks to see if the bookmarks are saved properly

As the original bug, the bookmarks are saved properly, which can also be seen in the video as the goto next bookmark command works correctly. The issue is only with the signs in the sign column not appearing

**Comment by tomasky** [comment]
weird， Have you modified this plugin yourself? What's your version of nvim?

**Comment by chrisgrieser** [comment]
No, I have made no modifications. I use nvim 0.9

**Comment by tomasky** [comment]
try this:
```lua
   ["tomasky/bookmarks.nvim"] = {
      -- opt = true,
      -- after = "telescope.nvim",
      event = "BufWinEnter",
      config = function()

      require('bookmarks').setup {}

```

**Comment by chrisgrieser** [comment]
disabling lazy loaind, *then* deleting all bookmarks, then restarting and setting new bookmarks seems to do the trick 🤔

**Comment by tomasky** [comment]
try lazy loading  with:
```lua
      event = "BufWinEnter",

```

**Comment by chrisgrieser** [comment]
"BufWinEnter" does not work, only lazy-loading event that seems to work is `VimEnter`

**Comment by chrisgrieser** [comment]
anyway, closing this, since `VimEnter` seems to work

**Comment by WikiLiu** [comment]
> ot work, only lazy-loading event that seems to work is `VimEnter`

still not stable, some marks diappear after restart, even show other project recorded.

**Comment by rafaelsmgomes** [comment]
Same
