### ISSUE TITLE
Conflict with gitsigns plugin

### ISSUE THREAD

**Issue by kobzar** [tomasky/bookmarks.nvim#5]
When we are use gitsigns plugin the bookmarks isnt working. 
But on the same time another plugin like 
```
		"yaocccc/nvim-foldsign",
```
Work normaly
![image](https://user-images.githubusercontent.com/1912842/233829427-ec3fea8b-38e0-499a-a7bd-fc58c36aaf83.png)

**Comment by tomasky** [comment]
gitsign and bookmark sign are on the same line?

**Comment by kobzar** [comment]
I think yes. As i understand bookmarks plugin try to use the same vertical line that gitsigns plugin.
So, if i make commit - my green line is going out and marks icons is visible (the same actions with other git statuses new/deldted line). But if line is marked by gitsigns changes - bookmarks isnt show the icons. 

But as i say before, the "yaocccc/nvim-foldsign" plugin use another vertical line to show his statuses in the same time with gitsigns (i show it in imegr in previous post)

**Comment by tomasky** [comment]
try:
```lua
require('bookmarks').setup {
     sign_priority = 8,
}
```

**Comment by kobzar** [comment]
Thanks. This is work for me. Now all look fine.
