### ISSUE TITLE
Icons redraw issue

### ISSUE THREAD

**Issue by kobzar** [tomasky/bookmarks.nvim#6]
The icons not update/refresh before terminal focus will lost.

OS: Linux, OsX
Terminal: Iterm2, alacritty

The icons isn't load when file is open.
The icons not change after was edited by "mi"
Add/Remove new mark is worked normally.

After file was opened, or icon was changed by "mi" @f
need to lost focus of terminal and return. For example Alt+Tab or mouse action. 
After this action all icons is loaded and updated. 

Save file e.t.c. doesn't help.

**Comment by tomasky** [comment]
please provide some video about this.

**Comment by kobzar** [comment]
Yes. All working fine. Thanks for quick fix.
